# The following workflow executes a diamond workflow
#
#   A
#  / \
# B   C
#  \ /
#   D
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
  - name: inner-diamond
    dag:
      tasks:
      - name: A1
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: A1
      - name: B1
        dependencies: [A1]
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: B1
      - name: C1
        dependencies: [A1]
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: C1
  - name: diamond
    dag:
      tasks:
      - name: A
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: A
      - name: B
        dependencies: [A]
        template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: B
      - name: C
        dependencies: [A]
        template: inner-diamond
        arguments:
          parameters:
          - name: message
            value: C