apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: whalesay-template
    inputs:
      parameters:
      - name: message
        value: "12"
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a
        templateRef:
          name: workflow-template-inner-steps
          template: inner-steps
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b
        templateRef:
          name: workflow-template-whalesay-template
          template: whalesay-template
        arguments:
          parameters:
          - name: message
            value: "hello2b"
