# Like parameters, artifacts can be "passed" to a template as well.
# In this example, the 'kubectl-input-artifact' template requires
# that an an artifact named 'kubectl' is supplied as an input,
# which it will place in /usr/local/bin/kubectl. This keeps the
# template more composable/flexible, than if the location was
# hard-wired inside the template.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-artifacts-
  labels:
    paiflow-pipelines-node-token: "pai-node-14o622p7lym0vb8wcb1"
    paiflow-pipelines-parent-user-id: "1557702098194904"
    paiflow-pipelines-pipeline-id: "15c3b000b5c74427c9c74a6a6e15e2b22"
    paiflow-pipelines-root-node-token: "1pai-node-w761w6d58f8be9xbnn"
    paiflow-pipelines-root-pipeline-id: "1fda7f0a92d784864a15a9ae011f3185f"
    paiflow-pipelines-run-token: "1pai-flow-ao65m05ndbjd7xmt6q"
    paiflow-pipelines-user-id: "1557702098194904"
spec:
  entrypoint: kubectl-input-artifact
  arguments:
    artifacts:
    - name: kubectl
      http:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl

  templates:
  - name: kubectl-input-artifact
    inputs:
      artifacts:
      - name: kubectl
        path: /usr/local/bin/kubectl
        mode: 0755
    container:
      image: debian:9.4
      command: [sh, -c]
      args: ["kubectl version"]
