# This example demonstrates the how to refer to input and output artifact paths.
# Referring to the path instead of copy/pasting it prevents errors when paths change.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-path-placeholders-
  labels:
    paiflow-pipelines-node-token: "pai-node-14o622p7lym0vb8wcb1"
    paiflow-pipelines-parent-user-id: "1557702098194904"
    paiflow-pipelines-pipeline-id: "15c3b000b5c74427c9c74a6a6e15e2b22"
    paiflow-pipelines-root-node-token: "1pai-node-w761w6d58f8be9xbnn"
    paiflow-pipelines-root-pipeline-id: "1fda7f0a92d784864a15a9ae011f3185f"
    paiflow-pipelines-run-token: "1pai-flow-ao65m05ndbjd7xmt6q"
    paiflow-pipelines-user-id: "1557702098194904"
spec:
  entrypoint: head-lines
  arguments:
    parameters:
    - name: lines-count
      value: 3
    artifacts:
    - name: text
      raw:
        data: |
          1
          2
          3
          4
          5
  templates:
  - name: head-lines
    inputs:
      parameters:
      - name: lines-count
      artifacts:
      - name: text
        path: /inputs/text/data
    outputs:
      parameters:
      - name: actual-lines-count
        valueFrom:
          path: /outputs/actual-lines-count/data
      artifacts:
      - name: text
        path: /outputs/text/data
    container:
      image: busybox
      command: [sh, -c, 'mkdir -p "$(dirname "{{outputs.artifacts.text.path}}")" "$(dirname "{{outputs.parameters.actual-lines-count.path}}")" ; head -n {{inputs.parameters.lines-count}} < "{{inputs.artifacts.text.path}}" | tee "{{outputs.artifacts.text.path}}" | wc -l > "{{outputs.parameters.actual-lines-count.path}}"']
