apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: input-artifact-raw-
  labels:
    paiflow.pipelines.run.id: "11"
    paiflow.pipelines.user.id: "dsf"
spec:
  entrypoint: raw-contents
  templates:
  - name: raw-contents
    inputs:
      artifacts:
      - name: myfile
        path: /tmp/file
        raw:
          data: |
            this is
            the raw file
            contents
    outputs:
      artifacts:
      - name: myfile
        path: /tmp/file2
        raw:
          data: |
            this is output content
    container:
      image: alpine:latest
      command: [/bin/sh -c]
      args: ["cat /tmp/file & touch /tmp/file2"]